services:
  web:
    build:
      context: ./dj
      dockerfile: Dockerfile
    container_name: wise
    command: sh -c "python wait_for_db.py && gunicorn wise.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000" # internal opening. Can be conected only from container inside docker. oposite of <ports:>
    # volumes:
    #   - /home/zoy/git/simple-django-project/dj/static:/app/static  # /app/static - internal container path to volume for django app
    depends_on:
      - db
    environment:
      - DATABASE_NAME=django_db
      - DATABASE_USER=django_user
      - DATABASE_PASSWORD=django_pass
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:15
    container_name: wise_db
    restart: always
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass

  nginx:
    image: nginx:alpine-perl
    container_name: wise_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/zoy/git/simple-django-project_wise/dj/static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
